#Image
FROM openjdk:11.0.5 AS builder
#Enviroment Variable
ENV APP_HOME=/root/dev/BeverageService
ENV SWAGGER_JSON=/root/dev/BeverageService/src/main/resources/beverage.yaml
ENV PORT 8080
# Working Directory
WORKDIR $APP_HOME
#COPY ALL THE STUFF
COPY . $APP_HOME
#Run the build
RUN ./gradlew build

EXPOSE 8080

FROM openjdk:11.0.5-jre
WORKDIR /root/
COPY  --from=builder /root/dev/BeverageService/build/libs/BeverageService-all.jar .

ENTRYPOINT ["java", "-Dspring.profiles.active=localdocker","-jar", "BeverageService-all.jar", "Server.jar"]